language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
- docker build -t dshrout/udagram-frontend:v7 ./udagram-frontend
- docker build -t dshrout/reverseproxy:v6 ./udagram-reverseproxy
- docker build -t dshrout/udagram-api-user:v7 ./udagram-api-user
- docker build -t dshrout/udagram-api-feed:v7 ./udagram-api-feed


after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push dshrout/udagram-frontend:v7
- docker push dshrout/reverseproxy:v6
- docker push dshrout/udagram-api-user:v7
- docker push dshrout/udagram-api-feed:v7


