language: node_js
node_js:
  - 12

services:
  - docker

before_install:
- docker build -t dshrout/udagram-frontend:v4 ./udagram-frontend
- docker build -t dshrout/reverseproxy:v4 ./udagram-reverseproxy
- docker build -t dshrout/udagram-api-user:v4 ./udagram-api-user
- docker build -t dshrout/udagram-api-feed:v4 ./udagram-api-feed


# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push dshrout/udagram-frontend:v4
- docker push dshrout/reverseproxy:v4
- docker push dshrout/udagram-api-user:v4
- docker push dshrout/udagram-api-feed:v4


