apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  selector:
    service: backend-feed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080