apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-svc
  name: frontend-svc
spec:
  selector:
    service: frontend-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
