apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse-proxy
  name: reverseproxy
spec:
  selector:
    service: reverseproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
