apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    service: backend-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080